name: Ready the code and deploy
on: [push,workflow_dispatch]
jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: Print working dir
        run: |
         pwd
         ls -a
         echo $GITHUB_WORKSPACE