name: Ready the code and deploy
on: [push,workflow_dispatch]
jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: capying the code
        uses: actions/checkout@v4

      - name: upgrade node version
        uses: actions/setup-node@v4
        with:
          node-version: 22.12

      - name: check version
        run: |
          node -v
          ls -a

      - name: install dependance
        run: npm i  

      - name: test the code
        run: npm run test       